[package]
name = "cht"
version = "0.1.2"
authors = ["Gregory Meyer <me@gregjm.dev>"]
edition = "2018"
description = "Lockfree resizeable concurrent hash table."
repository = "https://github.com/Gregory-Meyer/cht"
readme = "README.md"
license = "MIT"

[dependencies]
ahash = "0.2"
crossbeam-epoch = "0.7"

[dev-dependencies]
criterion = "0.3"
hashbrown = "0.6"
lock_api = "0.3"
num_cpus = "1.10"
parking_lot = "0.9"

[[bench]]
name = "cht"
harness = false

[[bench]]
name = "mutex"
harness = false
