[package]
name = "cht"
version = "0.3.0"
authors = ["Gregory Meyer <me@gregjm.dev>"]
edition = "2018"
description = "Lockfree resizeable concurrent hash table."
repository = "https://github.com/Gregory-Meyer/cht"
readme = "README.md"
license = "MIT"

[dependencies]
ahash = "^0.3.2"
crossbeam-epoch = "^0.8.2"

[dev-dependencies]
criterion = "^0.3.1"
hashbrown = "^0.7.0"
lock_api = "^0.3.3"
num_cpus = "^1.12.0"
parking_lot = "^0.10.0"

[[bench]]
name = "cht"
harness = false

[[bench]]
name = "mutex"
harness = false
